Associations
nunegabriel/OOP-school-library pull request #3
Opened 2023-01-19 17:08 UTC by nunegabriel

In this pull request I did the following:

- [ ] Created a class Classroom with Setter and getter for @label 
- [ ]  Created the has-many/belongs-to relationship between Classroom and Student.
- [ ] Created a class Book with the following:
@title and @author instance variables, should be initialized in the constructor.
- [ ] Create a class Rental with the following:
@date instance variable, should be initialized in the constructor.
Setter and getter for @date (remember about attr_accessor).
- [ ]  Created the has-many side of Book and Rental (a book has many rentals).
- [ ] Created the belongs-to side of Rental and Book (a rental belongs to a book).
- [ ] Created the has-many side of Person and Rental (a person has many rentals).
- [ ] Created the belongs-to side of Rental and Person (a rental belongs to a person).
- [ ] Modified the constructor of Rental so Book and Person are set in it.

2023-01-19 17:34 UTC, Ghiftee requested changes
## STATUS: CHANGES REQUIRED ♻️♻️
Hello @nunegabriel  👋🏽 

Good job working on the project so far! 
To highlight 👍🏽 
✔️ You created classes
✔️ Associations were set up
✔️ Your README is professional

However, there are some issues that you need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- For best practice, I suggest writing your commit messages in lowercase letters and capitalizing only the first letter.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-01-19 17:34 UTC, Ghiftee commented on person.rb
> +    @rentals = []
- [ ] Kindly create a method for adding rentals  e.g
```ruby
def add_rental(book, date)
    Rental.new(date, book, self)
  end
```

2023-01-19 17:34 UTC, Ghiftee commented on rental.rb
> +  def initialize(date)
- [ ] The constructor of Rental should be modified so Book and Person are set in it to break the many-to-many relationship. e.g
`def initialize(date, book, person)`
You can read more about this [here](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#many-to-many-relationship)

2023-01-20 09:18 UTC, mikethreels approved these changes
Hi Gabby, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- linters are passing
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-20 10:34 UTC, merged